// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface HomepageStoryblok {
  title?: string;
  description?: string;
  component: "homepage";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (HomepageStoryblok | PageStoryblok)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}
