import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import StoryblokProvider from './context/StoryblokProvider';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'LLevate un Amigo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div id="layout__wrapper">{children}</div>
        </body>
      </html>
    </StoryblokProvider>
  );
}
